import Product_1 from "../../../public/assets/images/Products/1.png";
import Product_2 from "../../../public/assets/images/Products/2.png";
import Product_3 from "../../../public/assets/images/Products/3.png";
import Product_4 from "../../../public/assets/images/Products/4.png";

const products = [
  {
    id: 1,
    image: Product_1,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 2,
    image: Product_2,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 3,
    image: Product_3,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 4,
    image: Product_4,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 5,
    image: Product_1,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 6,
    image: Product_2,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 7,
    image: Product_3,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
  {
    id: 8,
    image: Product_4,
    title: "Light Grey Yoga Shorts",
    subtitle: "Seamless fitting | Comfortable",
    mrp: "190",
    sp: "129",
    rating: 4.7,
    review: "202",
    badge: "Trending Now",
  },
];

export default products;